# Generated by Django 5.1 on 2024-08-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Customer",
            new_name="customer",
        ),
    ]
