# Generated by Django 5.1 on 2024-08-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_customer_order_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
