# Generated by Django 5.1 on 2024-08-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
