# Generated by Django 5.1 on 2024-08-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
