# Generated by Django 5.1 on 2024-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
