# Generated by Django 5.1 on 2024-08-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_cart_total_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
