# Generated by Django 5.1 on 2024-08-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_order_status_alter_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
